name: tcoe-679

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: HTTP Request Action
        id: http_request
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          url: https://ds.cloud.lhsystems.com/service/rest/v1/components?repository=tcoe-679
          username: "admin"
          password: ${{ secrets.NEXUS_PASSWORD }}
          method: 'POST'
          data: '{ "raw.directory" : "test", "raw.asset1.filename" : "payload.txt" }'
          files: '{ "raw.asset1" : "payload.txt" }'

      - name: Show Response
        run: echo ${{ steps.http_request.outputs.response }}
